import { Button } from '@/common/components/button/Button'
import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>My component library</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Button label="Click me" startIcon='pencil' />
      </main>
    </>
  )
}
